config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'landing#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :user, through: :user_stocks

  validates :name, :ticker, presence: true

  # Use 'self.' to make it a class method
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: ENV["IEX_API_KEY"] || Rails.application.credentials.iex_client[:sandbox_api_key], 
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    # client.post('ref-data/isin', isin: ['US0378331005'], token: 'secret_token') # [{'exchange' => 'NAS', ..., 'symbol' => 'AAPL'}, {'exchange' => 'ETR', ..., 'symbol' => 'APC-GY']

    begin
      new(
        ticker: ticker_symbol.upcase, 
        name: client.company(ticker_symbol).company_name, 
        last_price: client.price(ticker_symbol)
        )
    rescue => exception
      return nil
    end

  end

  def self.check_db(ticker_symbol)
    ticker_symbol.upcase!
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
    stocks.count < 30
  end

  def stock_already_tracked?(ticker_symbol)
    ticker_symbol.upcase!
    stock = Stock.check_db(ticker_symbol)
    return false unless stock

    stocks.where(id: stock.id).exists?
  end

  def can_track_stock?(ticker_symbol)
    ticker_symbol.upcase!
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController


  def search

    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        # Here we were just rendering the html file:
        # render 'users/my_portfolio'
        
        # Now we're using ajax so we'll have to 'respond to'
        # a js partial instead:
        respond_to do |format|
          format.js { render partial: 'users/result'}
        end
      else
        # Same change necessary here:
        # redirect_to my_portfolio_path
        # Note add the '.now' to flash to avoid persistant flash messages!
        respond_to do |format|
          flash.now[:alert] = "Could not find that symbol"
          format.js { render partial: 'users/result'}
        end
      end

    else
      # And here...
      # flash[:alert] = "Enter a symbol to search"
      # redirect_to my_portfolio_path
      respond_to do |format|
        flash.now[:alert] = "Enter a symbol to search"
        format.js { render partial: 'users/result'}
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was added to portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} removed"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<div class="row">
    <div class="col-9">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Email</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @friends.each do |friend| %>
            <tr>
              <td><%= friend.email %></td>
              <td><%= friend.first_name %></td>
              <td><%= friend.last_name %></td>
              <td><%= link_to 'Remove', '#', method: :delete, data: {confirm: 'Are you sure?'},
                    class: 'btn btn-sm btn-warning' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>  
    </div>
  </div>

app/views/landing/index.html.erb
<h3>Stock Soup</h3>
<p>All your stock are belong to me!</p>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Nav -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
      <div class="container">
        <%= link_to 'Stock Soup', root_path, class: 'navbar-brand' %>
        <% if current_user %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
                <%= link_to 'Portfolio', my_portfolio_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Friends', my_friends_path, class: 'nav-link' %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                    <%= fa_icon 'edit' %> Edit Profile
                  <% end %>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            </ul>
            <ul class='navbar-nav ml-auto'>
              <li class='.nav-item user-name'>
                <%= fa_icon 'user'%> <%= current_user.full_name %>
              </li>
              <li class='nav-item'>
                <%= link_to("Logout", destroy_user_session_path, 
                  class: "btn btn-xs btn-danger logout-button", method: :delete) %>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
          <% end %>
      </div>
    </nav>
    <!-- END NAV -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- NAV -->
    <%= render 'layouts/navigation' %>

    <!-- BODY -->
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
    <div class="col-9">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_stocks.each do |stock| %>
            <tr>
              <th scope="row"><%= stock.ticker %></th>
              <td><%= stock.name %></td>
              <td><%= stock.last_price %></td>
              <td>
                <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'},
                    class: 'btn btn-sm btn-warning' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>  
    </div>
  </div>

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong><%= @stock.ticker%>
    <strong>Name: </strong><%= @stock.name%>
    <strong>Price: </strong><%= @stock.last_price%>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to '+', user_stocks_path(user: current_user, ticker: @stock.ticker), 
          class: 'btn btn-xs btn-success', method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        already tracking
        <% if !current_user.under_stock_limit? %>
          30 Stocks
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker)%>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
<%# Note we need to escape the javascript - we do that with 'j' %>
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/my_friends.html.erb
<h3>Friends</h3>

<% if !@friends.empty? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h3>Watch List</h3>

<div class="search-area">
  <h5>Search Stocks</h5>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "stock ticker symbol", autofocus: true, class: "form-control form-control-lg"%>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%# Results are set from _result.js.erb - which is set in the controller %>
<div id="results">

</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>  
  